# Generated by Django 2.0.2 on 2018-08-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.CharField(default=None, max_length=30, null=True)),
                ('lat', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MineCrop_app.Address')),
            ],
        ),
        migrations.CreateModel(
            name='HashtagKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(default=None, max_length=200)),
                ('tweet', models.CharField(default=None, max_length=300)),
                ('date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(default=None, max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('tweet', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(default=None, max_length=200)),
                ('tweet', models.CharField(default=None, max_length=300)),
                ('location', models.CharField(default=None, max_length=200)),
                ('date', models.DateTimeField(default=None)),
                ('isTrained', models.NullBooleanField(default=None)),
                ('coordinates', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MineCrop_app.Coordinate')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='product',
            field=models.ManyToManyField(to='MineCrop_app.Product'),
        ),
        migrations.AddField(
            model_name='address',
            name='coordinates',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MineCrop_app.Coordinate'),
        ),
        migrations.AlterUniqueTogether(
            name='tweet',
            unique_together={('userid', 'tweet')},
        ),
    ]
