# Generated by Django 2.0.2 on 2018-08-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MineCrop_app', '0002_auto_20180825_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='farmer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MineCrop_app.Farmer'),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MineCrop_app.Product'),
        ),
    ]
