# Generated by Django 2.0.2 on 2018-08-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MineCrop_app', '0004_auto_20180826_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
